### PR TITLE
data: Add icon to AppStream metainfo

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
The icon is from https://github.com/fleet-commander/fleet-commander.github.io/blob/master/img/favicon57-7d2e27eb.png.  I guess it would be better to have a dedicated 64x64 one.

**Comment by olivergs** [comment]
Thank you very much @mvollmer !

**Comment by mvollmer** [comment]
@olivergs, are you happy with the actual icon?

**Comment by olivergs** [comment]
Yes, is the icon I would use :) Thanks

**Pull request merged**
