### PR TITLE
logger: Fixed firefox preference parsing code

### PR DESCRIPTION
**Pull request by olivergs**

### CODE REVIEW

**Comment by olivergs** [comment]
What I understood when we agreed to do that was that we could save the value as a json string.

The reason is done like this is because we need a key for each setting. THat key is the preference name, so I need to extract it from the preference data anyway.

The other thing I found, is that all preferences are named as dotted separated alphanumeric strings by convention, but  after this comment I went to about:config and I was able to add whatever value in the preference name (quotes, commas, whatever), so separate the values could be unreliable for custom preferences added by the user.

The way of keeping all in a JSON string is ok, but we still need a way to identify each setting individually.

**Comment by aruiz** [comment]
> What I understood when we agreed to do that was that we could save the value as a json string.
What I meant when we discussed it was that as a safety measure, we want to parse as a JSON list
'["key", "value"]', that's the safest and simplest way. You can store it however you think is consistent inside the profile, I'm talking strictly about parsing here.

**Comment by olivergs** [comment]
Ok. In that way, when I parse that as a JSON string, the list first element is they key, and the second one is the value.

I will modify it then and push the changes.

**Comment by olivergs** [comment]
Doing this using the JSON parse approach leads me to this error:

I have this preference:

```
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"bookmarks-menu-button\",\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"urlbar-container\",\"search-container\",\"downloads-button\",\"library-button\",\"abp-toolbarbutton\",\"qrcodeaddon-16\",\"action-button--jid0-9xfbwuwnvyx4wwsfbwmcm4jj69ejetpack-self-destructing-cookies\",\"ublock0-button\",\"VimFxButton\",\"ublock0_raymondhill_net-browser-action\",\"screenshots_mozilla_org-browser-action\",\"sidebar-button\",\"chrome-gnome-shell_gnome_org-browser-action\",\"preferences-button\",\"_4b6e6674-681a-45a4-98db-7c7d03df3560_-browser-action\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"]},\"seen\":[\"abp-toolbarbutton\",\"loop-button\",\"pocket-button\",\"developer-button\",\"action-button--jid0-9xfbwuwnvpx4wwsfbwmcm4jj69ejetpack-self-destructing-cookies\",\"ublock0-button\",\"VimFxButton\",\"ublock0_raymondhill_net-browser-action\",\"webide-button\",\"screenshots_mozilla_org-browser-action\",\"chrome-gnome-shell_gnome_org-browser-action\",\"_4b6e6274-681a-45a4-98db-7c7d03df73560_-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":13,\"newElementCount\":3}");
```

And I do this to parse it (it is not enought to use square brackets, we need to create an object to be able to parse JSON data)

```
JSON.parse('{"data": ["browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"bookmarks-menu-button\",\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"urlbar-container\",\"search-container\",\"downloads-button\",\"library-button\",\"abp-toolbarbutton\",\"qrcodeaddon-16\",\"action-button--jid0-9xfbwuwnvyx4wwsfbwmcm4jj69ejetpack-self-destructing-cookies\",\"ublock0-button\",\"VimFxButton\",\"ublock0_raymondhill_net-browser-action\",\"screenshots_mozilla_org-browser-action\",\"sidebar-button\",\"chrome-gnome-shell_gnome_org-browser-action\",\"preferences-button\",\"_4b6e6674-681a-45a4-98db-7c7d03df3560_-browser-action\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"]},\"seen\":[\"abp-toolbarbutton\",\"loop-button\",\"pocket-button\",\"developer-button\",\"action-button--jid0-9xfbwuwnvpx4wwsfbwmcm4jj69ejetpack-self-destructing-cookies\",\"ublock0-button\",\"VimFxButton\",\"ublock0_raymondhill_net-browser-action\",\"webide-button\",\"screenshots_mozilla_org-browser-action\",\"chrome-gnome-shell_gnome_org-browser-action\",\"_4b6e6274-681a-45a4-98db-7c7d03df73560_-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":13,\"newElementCount\":3}"]}')
```

This gives me the error

```
SyntaxError: JSON.parse: expected ',' or ']' after array element at line 1 column 47 of the JSON data
```
Because the escaping is not working and JSON is trying to parse the data inside the value.

I'm currently thinking a way to fix this special case.

**Comment by aruiz** [comment]
Because you are using single commas rather than double

**Comment by olivergs** [comment]
Also tried using double quotes and was not able to parse it. The trick was to use template literals and raw strings:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Raw_strings

Currently testing integration part, but seems it works at code/test level.

**Comment by olivergs** [comment]
Now we use the JSON parsing method and it works as expected in the admin part. Currently checking the client part works as expected with the change, but this side can be reviewed.

**Comment by olivergs** [comment]
Opened https://github.com/fleet-commander/fc-client/issues/14 to fix data retrieval at client side.

**Pull request merged**
