### PR TITLE
data: Add AppStream metainfo

### PR DESCRIPTION
**Pull request by mvollmer**
This makes the Fleet Commander admin interface appear as an
installable application inside Cockpit.

### CODE REVIEW

**Comment by mvollmer** [comment]
I have not tested this in any way... I haven't even compiled fc-admin.

**Comment by mvollmer** [comment]
You can also have an icon and screenshots, of course.

**Comment by aruiz** [comment]
This is great stuff, we will give it a shot. Do we need any specific version of Cockpit for this to work?

**Comment by mvollmer** [comment]
> Do we need any specific version of Cockpit for this to work?

Whoops, yes, sorry for not mentioning this here.  You need this branch/PR of Cockpit: https://github.com/cockpit-project/cockpit/pull/7076

**Comment by olivergs** [comment]
Awesome!. I'm currently finishing some updates in freeipa related packages, but as soon as I finish that I will take a look at this.

Thanks @mvollmer

**Comment by mvollmer** [comment]
> but as soon as I finish that I will take a look at this.

Great!  Let me know what you want to have in the metainfo (text, icons, screenshots), and I'll update the XML.

**Comment by mvollmer** [comment]
Ouch, I have misunderstood how icons and screenshots are handled by appstream-builder.  I thought you could just include them in the upstream metainfo file (the one added in this PR).

So we have to handle icons and screenshots separately.  More once I know now.

**Pull request merged**
