### PR TITLE
Add support for remote-viewer

### PR DESCRIPTION
**Pull request by stanislavlevin**
Currently, only spice-html5 is supported as a SPICE client to
send data and translate the data from the VM.
    
According to [0]:
> Spice has a prototype Web client which runs entirely within a modern
> browser. It is limited in function, a bit slow, and lacks support for
> many features of Spice (audio, video, agents just to name a few).
> However, it is surprisingly functional, and certainly a useful proof
> of concept.
    
In the meantime, the recommended SPICE client application is virt-viewer.
So, it's good to give the user a choice.

### The proposed remote-viewer(SPICE TLS and SPICE Plain) flow:

_Prerequisites_:
manual step for now: the user has to prepare TLS stuff for SPICE TLS [1]

1) WEBUI: user authenticates to cockpit as the domain user
2) WEBUI: user launches FC plugin for cockpit
3) cockpit host: FC dbus service manages libvirt host via SSH
4) cockpit host: FC dbus service started VM on libvirt host
5) libvirt host: qemu setups channel ('unix') for private communication between host and guest. This channel is used to listen changes from VM.
   The writer is fleet-commander-logger (sends the data to '/dev/virtio-ports/org.freedesktop.FleetCommander.0').
   The reader end is exposed to the host as unix domain socket at '/run/user/$ID/$SOCKET_NAME'
6) cockpit host: FC dbus service creates SSH tunnel which forwards unix domain socket('/run/user/$ID/$LOGGER_SOCKET') connections to libvirt host and listening unix domain socket created before
7) cockpit host: cockpit creates channel which listens for VM changes on unix domain socket created before
    
8) WEBUI: browser downloads Connection File for remote-viewer and user run it.
    
9) SPICE TLS or Plain connection is established.

10) WEBUI: browser listens for DE changes via cockpit channel
    
So, the SPICE traffic goes directly to libvirt host, notify channel passes cockpit host.
    
    [0] https://www.spice-space.org/spice-html5.html
    [1] https://www.spice-space.org/spice-user-manual.html#_tls

Overview:
overview

Viewer setup:
viewer_setting

### CODE REVIEW

**Comment by stanislavlevin** [comment]
WIP, since I'm fixing/adding tests. Nevertheless, I'm opened to comments.

**Comment by olivergs** [comment]
Thank you very much. I will check it out ASAP. I'm trying to fix the samba problem first as it is critical right now, so as soon as I finish with that I will take a look to this feature.

**Comment by stanislavlevin** [comment]
@olivergs, thank you in advance!

**Comment by stanislavlevin** [comment]
Rebased.

**Comment by stanislavlevin** [comment]
Rebased to master.

**Comment by stanislavlevin** [comment]
- added support for Spice Plain via remote-viewer
- added new tests and fixed existing ones
- forward of logging of Logger to web browser console
- switch from jslint to eslint
- many cleanups and improvements

Ready for review.

**Comment by olivergs** [comment]
Thank you Stanislav. I will check this on Thursday.

**Comment by olivergs** [comment]
Tested in F32 and F33. Works for me perfectly.

Only some suggestions:

• Add status indication when connecting from external viewer in replacement of spice-html5 screen, telling the user the VM is running and accepting connections externally. Even showing the connection parameters to be introduced by hand could be useful.

• Specifying the user that have to install the virt-viewer to use the downloaded file could be also interesting

• The text for the button to reconnect should change to redownload the file or something more indicative of what is happening.

Have to review code, but I will do my best on that.

Good work!

**Comment by stanislavlevin** [comment]
Addressed suggestions.

**Comment by olivergs** [comment]
Thanks   @stanislavlevin . Will check it soon.

**Comment by olivergs** [comment]
Quite a good job @stanislavlevin . Tested it, reviewed the code and works for me. Thank you very much.

**Comment by stanislavlevin** [comment]
@olivergs, thank you for the review!

**Pull request merged**
