### PR TITLE
Fixed invalid signature for libsmb.Conn object. Fixes #275

### LINKED ISSUE #275: Samba 3 libsmb has changed Conn object signature
The Conn object has changed its signature, causing an error initializing a SMB connection in Active Directory module

@stanislavlevin located the change in this commit:
https://git.samba.org/?p=samba.git;a=commit;h=6f552204d4614ad97310fb4ab81a06d21d4b9af7

### PR DESCRIPTION
**Pull request by olivergs**
Removed the sign parameter from the libsmb.Conn object initialization.

### CODE REVIEW

**Comment by stanislavlevin** [comment]
```console
# git grep 'sign='
admin/fleetcommander/fcad.py:            self._get_server_name(), service, lp=parm, creds=creds, sign=False
tests/smbmock.py:    def __init__(self, servername, service, lp, creds, sign=False):
```

**Comment by stanislavlevin** [comment]
Please, also update `SMBMock`.

**Comment by stanislavlevin** [comment]
LGTM, thank you!

**Comment by olivergs** [comment]
Thanks for the review and the help @stanislavlevin :+1:

**Pull request merged**
